<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="flex-PC" ignored="0" name="Command line test" tests="6" failures="4" timestamp="2019-12-10T16:21:59 MSK" time="317.891" errors="0">
  <testcase name="testFib" time="0.045" classname="org.example.TestFib"/>
  <testcase name="testFib" time="0.043" classname="org.example.TestFib"/>
  <testcase name="testFib" time="0.028" classname="org.example.TestFib">
    <failure type="java.lang.IllegalArgumentException" message="Мы не считаем значения меньше 0 или больше 50!">
      <![CDATA[java.lang.IllegalArgumentException: Мы не считаем значения меньше 0 или больше 50!
at org.example.FibCalc.calc(FibCalc.java:17)
at org.example.TestFib.testFib(TestFib.java:36)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testFib -->
  <testcase name="testFib" time="0.048" classname="org.example.TestFib">
    <failure type="java.lang.IllegalArgumentException" message="Мы не считаем значения меньше 0 или больше 50!">
      <![CDATA[java.lang.IllegalArgumentException: Мы не считаем значения меньше 0 или больше 50!
at org.example.FibCalc.calc(FibCalc.java:17)
at org.example.TestFib.testFib(TestFib.java:36)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testFib -->
  <testcase name="testFib" time="0.062" classname="org.example.TestFib">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.example.TestFib.testFib() didn&amp;apos;t finish within the time-out 40">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.example.TestFib.testFib() didn't finish within the time-out 40
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- testFib -->
  <testcase name="testFib" time="317.79" classname="org.example.TestFib">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.example.TestFib.testFib() didn&amp;apos;t finish within the time-out 40">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.example.TestFib.testFib() didn't finish within the time-out 40
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- testFib -->
</testsuite> <!-- Command line test -->
